name: stackoverflow_users_app
description: "Stack Overflow users browser with clean architecture."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^8.1.3
  get_it: ^7.7.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3

  # Keep intl aligned with Flutter stable; remove override above if this resolves fine.
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter

  flutter_dotenv: ^5.0.2

  # Remove if unused:
  cupertino_icons: ^1.0.8
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.6.0

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.5.0

  # Testing helpers (recommended)
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/colors/
    - .env

flutter_gen:
  output: lib/generated/
  line_length: 100
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml


patrol:
  app_name: stackoverflow_users_app
  android:
    package_name: com.example.stackoverflow_users_app
  ios:
    bundle_id: com.example.stackoverflowUsersApp