enum ReputationHistoryType {
  askerAcceptsAnswer,
  askerUnacceptAnswer,
  answerAccepted,
  answerUnaccepted,
  voterDownvotes,
  voterUndownvotes,
  postDownvoted,
  postUndownvoted,
  postUpvoted,
  postUnupvoted,
  suggestedEditApprovalReceived,
  postFlaggedAsSpam,
  postFlaggedAsOffensive,
  bountyGiven,
  bountyEarned,
  bountyCancelled,
  postDeleted,
  postUndeleted,
  associationBonus,
  arbitraryReputationChange,
  voteFraudReversal,
  postMigrated,
  userDeleted,
  exampleUpvoted,
  exampleUnupvoted,
  proposedChangeApproved,
  docLinkUpvoted,
  docLinkUnupvoted,
  docSourceRemoved,
  suggestedEditApprovalOverridden,

  // unexpected value
  unknown,
}
